### ISSUE TITLE
Restrict Egress for GitHub Actions

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/uds-security-hub#158]
**Issue Description:**

Our GitHub Actions workflows do not have restricted egress policies, which poses a security risk. Unrestricted egress can allow malicious actors to exfiltrate data or communicate with unauthorized endpoints.

**Proposed Solution:**

Implement egress restrictions for all GitHub Actions workflows using the [step-security/harden-runner](https://github.com/step-security/harden-runner) action. This action will block all egress traffic except to a specified list of allowed endpoints.

**Action Plan:**

1. **Integrate `harden-runner` Action:**
   Add the `harden-runner` action to our workflows with the following configuration:
   ```yaml
   name: Harden Runner
   uses: step-security/harden-runner@17d0e2b
   with:
     disable-sudo: true
     egress-policy: block
     allowed-endpoints: |
       api.github.com:443
       github.com:443
       objects.githubusercontent.com:443
       proxy.golang.org:443
       storage.googleapis.com:443
       sum.golang.org:443
   ```

2. **Audit and Update Workflows:**
   - Review all existing workflows to ensure they comply with the new egress policy.
   - Update workflows to include the `harden-runner` action where necessary.

3. **Testing:**
   - Test the updated workflows to ensure they function correctly with the existing egress restrictions.
   - Monitor for any issues or failures and adjust the allowed endpoints list as needed.

**Benefits:**

- **Enhanced Security:** Restricting egress traffic reduces the risk of data exfiltration and unauthorized communications.
- **Compliance:** Helps meet security compliance requirements by enforcing strict network policies.
